### ISSUE TITLE
Additional Headers not defined in cloudservice.getHeadersList()

### ISSUE THREAD

**Issue by aselafernando** [ddurdle/Amazon-Cloud-Drive-for-KODI#34]
The definition of getHeadersList(self) in cloudservice.py causes the following error as it does not take into account the additional header required for requesting byte ranges.

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: getHeadersList() got an unexpected keyword argument 'additionalHeader'
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.acd-testing/default.py", line 1274, in <module>
                                                service.downloadEncfsFile(mediaURL, package, playbackURL=encfs_target + 'encfs.mp4', force=False,folderName=str(encfs_source) + str(file), playback=resolvedPlayback,item=item, player=player, srt=encfsSubTitles)
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.acd-testing/resources/lib/cloudservice.py", line 644, in downloadEncfsFile
                                                req = urllib2.Request(mediaURL.url, None, self.getHeadersList(additionalHeader='Range', additionalValue='bytes='+str(xbmcvfs.File(playbackFile).size())+'-'+str(package.file.size)))
                                            TypeError: getHeadersList() got an unexpected keyword argument 'additionalHeader'
                                            -->End of Python script error report<--
```

Fix:

cloudservice.py:
```python
#Change getHeadersList to be
def getHeadersList(self, additionalHeaders={}):
        headers = { 'User-Agent' : self.user_agent }
        headers |= additionalHeaders
        return headers

#Change Function calls that need additional headers such as in downloadEncfsFile and downloadMediaFile
req = urllib2.Request(mediaURL.url, None, self.getHeadersList(additionalHeader='Range', additionalValue='bytes='+str(xbmcvfs.File(playbackFile).size())+'-'+str(package.file.size)))
#To
req = urllib2.Request(mediaURL.url, None, self.getHeadersList({'Range': 'bytes='+str(xbmcvfs.File(playbackFile).size())+'-'+str(package.file.size)}))
```

This has the additional benefit of allowing multiple additional headers if required in the future.

**Comment by aselafernando** [comment]
Created Pull Request #35

**Comment by ddurdle** [comment]
promoted to stable
